checker:
  unupdated-zone:
    sync-time: 4h
  ibc-data:
    sync-time: 1h
  chain-id:
    sync-time: 1h
    check-last-days: 7
    ignore-chain-ids: ${CHAIN_ID_IGNORE}
  unupdated-price:
    sync-time: 1h
    allowed-time: 1h

notify:
  emulator:
    enabled: ${EMULATOR_MODE:false}
  telegram:
    api-telegram-org: 'https://api.telegram.org'
    send-message-path: /{token}/sendMessage
    token: ${TOKEN}
    chats: 
      default:
        chat-id: ${CHAT_ID}
      price: 
        chat-id: ${PRICE_CHAT_ID}


spring:
  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5432/moz_db}
    username: ${DB_USER:postgres}
    password: ${DB_PASS:postgres}
    hikari:
      maximum-pool-size: 1
      data-source-properties:
        stringtype: unspecified

logging:
  level:
    com.mapofzones.statereporter: DEBUG
