checker:
  host: http://<ip>:<port>
  sync-time: ${SYNC_TYME} # 14400000 # in milliseconds -> 1000 * 60 * 60 * 4 = 14 400 000 = 4 hour
#  telegram-chat-id: ${CHAT_ID} # this var env using directly in TelegramConstants
#  telegram-token-id: ${TOKEN}  # this var env using directly in TelegramConstants

spring:
  main:
    web-application-type: none

    jpa:
      open-in-view: false

      hibernate:
        ddl-auto: validate

      properties:
        hibernate:
          schema_update:
            unique_constraint_strategy: RECREATE_QUIETLY
          jdbc:
            lob:
              non_contextual_creation: true

