checker:
  unupdated-zone:
    sync-time: 4h
  ibc-data:
    sync-time: 1h
  chain-id:
    sync-time: 1h

notify:
  emulator:
    enabled: true

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/moz_db
    username: postgres
    password: postgres
    hikari:
      maximum-pool-size: 1
      data-source-properties:
        stringtype: unspecified
