endpoint:
  lcd:
    node-info: '/node_info'
    clients: '/ibc/core/client/v1/client_states?pagination.limit=1000000&pagination.key=%s'
    connections: '/ibc/core/connection/v1/connections?pagination.limit=1000000&pagination.key=%s'
    channels: '/ibc/core/channel/v1/channels??pagination.limit=1000000&pagination.key=%s'

spring:
  main:
    web-application-type: none

  jpa:
    open-in-view: false

    hibernate:
      ddl-auto: validate

    properties:
      hibernate:
        schema_update:
          unique_constraint_strategy: RECREATE_QUIETLY
        jdbc:
          lob:
            non_contextual_creation: true
