#  telegram-chat-id: ${CHAT_ID} # this var env using directly in TelegramConstants
#  telegram-token-id: ${TOKEN}  # this var env using directly in TelegramConstants

checker:
  unupdated-zone:
    sync-time: ${UNUPDATED_ZONE_SYNC_TYME}
  ibc-data:
    sync-time: ${IBC_DATA_SYNC_TYME}
  chain-id:
    sync-time: ${CHAIN_ID_SYNC_TYME}

notify:
  telegram:
    chat-id: ${CHAT_ID}
    token: ${TOKEN}
    api-telegram-org: 'https://api.telegram.org'
    send-message-path: /${TOKEN}/sendMessage
    enabled: true

spring:
  datasource:
    url: ${DB_URL}
    username: ${DB_USER}
    password: ${DB_PASS}
    hikari:
      data-source-properties:
        stringtype: unspecified
      maximum-pool-size: 1
